blank_lines_upper_bound = 1
brace_style = "PreferSameLine"
force_multiline_blocks = true
format_code_in_doc_comments = true
format_strings = true
merge_derives = false
newline_style = "Unix"
normalize_comments = true
reorder_impl_items = true
struct_lit_single_line = false
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
